# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: safeentry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsafeentry.proto\x12\tsafeentry\"b\n\x0f\x43heckIn_Request\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04nric\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x10\n\x08\x64\x61tetime\x18\x04 \x01(\t\x12\x0f\n\x07groupid\x18\x05 \x01(\x05\" \n\rCheckIn_Reply\x12\x0f\n\x07message\x18\x01 \x01(\t\"I\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04nric\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x10\n\x08\x64\x61tetime\x18\x04 \x01(\t\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0fHistory_Request\x12\x0c\n\x04nric\x18\x01 \x01(\t\";\n\rHistory_Reply\x12*\n\thistories\x18\x01 \x03(\x0b\x32\x17.safeentry.History_Item\"e\n\x0cHistory_Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04nric\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x12\n\ncheckin_dt\x18\x04 \x01(\t\x12\x13\n\x0b\x63heckout_dt\x18\x05 \x01(\t\"\x1d\n\rCheck_Request\x12\x0c\n\x04nric\x18\x01 \x01(\t\"4\n\x0b\x43heck_Reply\x12%\n\x06\x63hecks\x18\x01 \x03(\x0b\x32\x15.safeentry.Check_item\"c\n\nCheck_item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04nric\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x12\n\ncheckin_dt\x18\x04 \x01(\t\x12\x13\n\x0b\x63heckout_dt\x18\x05 \x01(\t2\xc7\x02\n\x10SafeEntryService\x12\x41\n\x07\x43heckin\x12\x1a.safeentry.CheckIn_Request\x1a\x18.safeentry.CheckIn_Reply\"\x00\x12\x32\n\x08\x43heckout\x12\x12.safeentry.Request\x1a\x10.safeentry.Reply\"\x00\x12\x41\n\x07History\x12\x1a.safeentry.History_Request\x1a\x18.safeentry.History_Reply\"\x00\x12\x33\n\tContacted\x12\x12.safeentry.Request\x1a\x10.safeentry.Reply\"\x00\x12\x44\n\x0e\x63heckContacted\x12\x18.safeentry.Check_Request\x1a\x16.safeentry.Check_Reply\"\x00\x62\x06proto3')



_CHECKIN_REQUEST = DESCRIPTOR.message_types_by_name['CheckIn_Request']
_CHECKIN_REPLY = DESCRIPTOR.message_types_by_name['CheckIn_Reply']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_REPLY = DESCRIPTOR.message_types_by_name['Reply']
_HISTORY_REQUEST = DESCRIPTOR.message_types_by_name['History_Request']
_HISTORY_REPLY = DESCRIPTOR.message_types_by_name['History_Reply']
_HISTORY_ITEM = DESCRIPTOR.message_types_by_name['History_Item']
_CHECK_REQUEST = DESCRIPTOR.message_types_by_name['Check_Request']
_CHECK_REPLY = DESCRIPTOR.message_types_by_name['Check_Reply']
_CHECK_ITEM = DESCRIPTOR.message_types_by_name['Check_item']
CheckIn_Request = _reflection.GeneratedProtocolMessageType('CheckIn_Request', (_message.Message,), {
  'DESCRIPTOR' : _CHECKIN_REQUEST,
  '__module__' : 'safeentry_pb2'
  # @@protoc_insertion_point(class_scope:safeentry.CheckIn_Request)
  })
_sym_db.RegisterMessage(CheckIn_Request)

CheckIn_Reply = _reflection.GeneratedProtocolMessageType('CheckIn_Reply', (_message.Message,), {
  'DESCRIPTOR' : _CHECKIN_REPLY,
  '__module__' : 'safeentry_pb2'
  # @@protoc_insertion_point(class_scope:safeentry.CheckIn_Reply)
  })
_sym_db.RegisterMessage(CheckIn_Reply)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'safeentry_pb2'
  # @@protoc_insertion_point(class_scope:safeentry.Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'safeentry_pb2'
  # @@protoc_insertion_point(class_scope:safeentry.Reply)
  })
_sym_db.RegisterMessage(Reply)

History_Request = _reflection.GeneratedProtocolMessageType('History_Request', (_message.Message,), {
  'DESCRIPTOR' : _HISTORY_REQUEST,
  '__module__' : 'safeentry_pb2'
  # @@protoc_insertion_point(class_scope:safeentry.History_Request)
  })
_sym_db.RegisterMessage(History_Request)

History_Reply = _reflection.GeneratedProtocolMessageType('History_Reply', (_message.Message,), {
  'DESCRIPTOR' : _HISTORY_REPLY,
  '__module__' : 'safeentry_pb2'
  # @@protoc_insertion_point(class_scope:safeentry.History_Reply)
  })
_sym_db.RegisterMessage(History_Reply)

History_Item = _reflection.GeneratedProtocolMessageType('History_Item', (_message.Message,), {
  'DESCRIPTOR' : _HISTORY_ITEM,
  '__module__' : 'safeentry_pb2'
  # @@protoc_insertion_point(class_scope:safeentry.History_Item)
  })
_sym_db.RegisterMessage(History_Item)

Check_Request = _reflection.GeneratedProtocolMessageType('Check_Request', (_message.Message,), {
  'DESCRIPTOR' : _CHECK_REQUEST,
  '__module__' : 'safeentry_pb2'
  # @@protoc_insertion_point(class_scope:safeentry.Check_Request)
  })
_sym_db.RegisterMessage(Check_Request)

Check_Reply = _reflection.GeneratedProtocolMessageType('Check_Reply', (_message.Message,), {
  'DESCRIPTOR' : _CHECK_REPLY,
  '__module__' : 'safeentry_pb2'
  # @@protoc_insertion_point(class_scope:safeentry.Check_Reply)
  })
_sym_db.RegisterMessage(Check_Reply)

Check_item = _reflection.GeneratedProtocolMessageType('Check_item', (_message.Message,), {
  'DESCRIPTOR' : _CHECK_ITEM,
  '__module__' : 'safeentry_pb2'
  # @@protoc_insertion_point(class_scope:safeentry.Check_item)
  })
_sym_db.RegisterMessage(Check_item)

_SAFEENTRYSERVICE = DESCRIPTOR.services_by_name['SafeEntryService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHECKIN_REQUEST._serialized_start=30
  _CHECKIN_REQUEST._serialized_end=128
  _CHECKIN_REPLY._serialized_start=130
  _CHECKIN_REPLY._serialized_end=162
  _REQUEST._serialized_start=164
  _REQUEST._serialized_end=237
  _REPLY._serialized_start=239
  _REPLY._serialized_end=263
  _HISTORY_REQUEST._serialized_start=265
  _HISTORY_REQUEST._serialized_end=296
  _HISTORY_REPLY._serialized_start=298
  _HISTORY_REPLY._serialized_end=357
  _HISTORY_ITEM._serialized_start=359
  _HISTORY_ITEM._serialized_end=460
  _CHECK_REQUEST._serialized_start=462
  _CHECK_REQUEST._serialized_end=491
  _CHECK_REPLY._serialized_start=493
  _CHECK_REPLY._serialized_end=545
  _CHECK_ITEM._serialized_start=547
  _CHECK_ITEM._serialized_end=646
  _SAFEENTRYSERVICE._serialized_start=649
  _SAFEENTRYSERVICE._serialized_end=976
# @@protoc_insertion_point(module_scope)
